app:
    name : demo
    title : demo
    domain : springbootSimple
    description :

server:
    servlet:
      context-path: /
    address: localhost
    port: 80
    error:
       path: /error

spring:
    profiles:
        active: @profiles.env.active@
    fastJson :
          unAutoResultInfoPaths: /swagger-resources, /v2/api-docs, /api/login, /error
    freemarker:
      templateLoaderPath: classpath:/templates/
      allow-request-override: false
      allowSessionOverride: false
      cache: true
      checkTemplateLocation: true
      contentType: text/html
      exposeRequestAttributes: false
      exposeSessionAttributes: false
      exposeSpringMacroHelpers: false
      suffix: .ftl
      templateEncoding: UTF-8
      spring.freemarker.settings:
                      locale: zh_CN
                      date_format: yyyy-MM-dd
                      time_format: HH:mm:ss
                      datetime_format: yyyy-MM-dd HH:mm:ss
                      classic_compatible: true
    mvc:
      static-path-pattern: /static/**
    cors:
       pathPatterns : /*
       allowedOrigin :  "*"
       allowedHeaders : x-requested-with,Content-Type
       allowedMethods : POST,GET,PUT,OPTIONS,DELETE
       maxAge : 3600
       allowedCredentials : true



mapper :
     mappers :
            - com.jd.virtual.training.dao.MyMapper
     not-empty : false
     identity : MYSQL